// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/trailstem/go-nextjs-rest-api/controller"
	"github.com/trailstem/go-nextjs-rest-api/repository"
	"github.com/trailstem/go-nextjs-rest-api/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB) (controller.IUserController, error) {
	iUserRepository := repository.NewUserRepository(db)
	iUserUsecase := usecase.NewUserUsecase(iUserRepository)
	iUserController := controller.NewUserController(iUserUsecase)
	return iUserController, nil
}
