// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/trailstem/go-nextjs-rest-api/controller"
	"github.com/trailstem/go-nextjs-rest-api/repository"
	"github.com/trailstem/go-nextjs-rest-api/usecase"
	"github.com/trailstem/go-nextjs-rest-api/validator"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB) (*AppControllers, error) {
	iUserRepository := repository.NewUserRepository(db)
	iUserValidator := validator.NewUserValidator()
	iUserUsecase := usecase.NewUserUsecase(iUserRepository, iUserValidator)
	iUserController := controller.NewUserController(iUserUsecase)
	iTaskRepository := repository.NewTaskRepository(db)
	iTaskValidator := validator.NewTaskValidator()
	iTaskUsecase := usecase.NewTaskUsecase(iTaskRepository, iTaskValidator)
	iTaskController := controller.NewTaskController(iTaskUsecase)
	appControllers := NewAppControllers(iUserController, iTaskController)
	return appControllers, nil
}

// wire.go:

// uc : userController
// tc : taskController
type AppControllers struct {
	UserController controller.IUserController
	TaskController controller.ITaskController
}

func NewAppControllers(uc controller.IUserController, tc controller.ITaskController) *AppControllers {
	return &AppControllers{
		UserController: uc,
		TaskController: tc,
	}
}
